- name: Install and run HTTPD
  hosts: myserver
  become: yes
  tasks:
    - name: Install HTTP Package
      yum:
        name: http
        state: present
    - name: Start HTTP Service
      service:
        name: httpd
        state: started
        enabled: yes
